- id: py3arch
  name: py3arch
  description: Checks dependencies between modules in your project. Define architectural constraints to enforce module boundaries.
  entry: py3arch
  pass_filenames: false # until py3arch can support multiple files
  language: python
  types: [python]
